apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-consumer-default-master-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drewby/argocd-manifests
    targetRevision: HEAD
    path: jal/cluster2/consumer
  destination:
    name: cluster2
    namespace: default-all
  syncPolicy:
    automated:
      prune: True
      selfHeal: True