apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster3-app1-nonprod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drewby/demo-apps
    targetRevision: HEAD
    path: app1
  destination:
    name: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
