apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster3-consumer-default-master-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drewby/argocd-manifests
    targetRevision: HEAD
    path: default/cluster3/consumer
  destination:
    name: cluster3
    namespace: default
  syncPolicy:
    automated:
      prune: True
      selfHeal: True