apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-nonprod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drewby/demo-apps
    targetRevision: HEAD
    path: app2
  destination:
    name: cluster2
    namespace: app2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true