apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-default-master-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kshitijcode/argocd-manifests
    targetRevision: master
    path: default/cluster1/consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: default-all
  syncPolicy:
    automated:
      prune: True
      selfHeal: True