apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-nonprod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/drewby/demo-apps
    targetRevision: HEAD
    path: app1
  destination:
    name: cluster1
    namespace: default

